config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  root 'welcome#index'

  devise_for :users

  
  get 'evidence_sources/my_submissions'
  get 'evidence_sources/new_submitted'
  get 'evidence_sources/rejected'
  get 'evidence_sources/accepted'
  get 'evidence_sources/published'
  get 'evidence_sources/all'

  resources :evidence_sources do
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evidence_item.rb
class EvidenceItem < ApplicationRecord
end

app/models/evidence_source.rb
class EvidenceSource < ApplicationRecord
    has_many :evidence_source_authors, dependent: :destroy
end

app/models/evidence_source_author.rb
class EvidenceSourceAuthor < ApplicationRecord
    belongs_to :evidence_source
end

app/models/evidence_source_research_design.rb
class EvidenceSourceResearchDesign < ApplicationRecord
  belongs_to :evidence_source
end

app/models/research_design_constant.rb
class ResearchDesignConstant < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :authenticate_user!
end

app/controllers/evidence_source_authors_controller.rb
class EvidenceSourceAuthorsController < ApplicationController
end

app/controllers/evidence_sources_controller.rb
class EvidenceSourcesController < ApplicationController
    
    def index
        published
    end
    
    def my_submissions
        # every user
        @evidence_sources = EvidenceSource.where 'creator_id=?', current_user.id
    end
    
    def new_submitted
        # moderator and administrator
        @evidence_sources = EvidenceSource.where 'status=?', 'NEW'
    end
    
    def rejected
        # admistrator ? maybe
        @evidence_sources = EvidenceSource.where 'status=?', 'REJECTED'
    end
    
    def accepted
        # analystv and administrator
        @evidence_sources = EvidenceSource.where 'status=?', 'ACCEPTED'
    end
    
    def published
        # every one
        @evidence_sources = EvidenceSource.where 'status=?', 'PUBLISHED'
    end
    
    def all
        @evidence_sources = EvidenceSource.all
    end
    
    def update
        # TODO
        puts 'this is update  # TODO'
        puts params
        puts params.require(:status)
        
        esid = params.require(:id)
        status = params.require(:status)
        
        evidence_source = EvidenceSource.find(esid)
        evidence_source[:status] = status
        evidence_source.save()
        
        puts evidence_source.id
        puts evidence_source.status
    end
    
    def new
        # @evidence_source = EvidenceSource
    end
    
    def create
        puts "this is EvidenceSourcesController::create"

        authors = params.require(:evidence_source)[:author]
        page_str = params.require(:evidence_source)[:page]
        
        @evidence_source = EvidenceSource.new(evidence_source_params)
        @evidence_source.status = 'NEW'
        @evidence_source.page_str = page_str
        
        _user = current_user
        @evidence_source.creator_id = _user.id
        @evidence_source.creator_email = _user.email
        
        unless page_str.nil?
            (b, c) = page_str.split('-')
            begin
                @evidence_source.page_begin = Integer(b)
                @evidence_source.page_cease = Integer(c)
            rescue
                puts "Exception while " + page_str
            ensure
            end
        end
        
        puts '*************'
        puts authors
        puts page_str
        puts @evidence_source

        puts '$$$$$$$$$$$$$$$$$$$$'
        
        puts 'ID: ' + @evidence_source.id.to_s
        @evidence_source.save
        puts 'ID: ' + @evidence_source.id.to_s
        
        author = @evidence_source.evidence_source_authors.create
        author.name = 'Junshu Wang'
        author.name_abbr = 'J. Wang'
        author.save
        
        author = @evidence_source.evidence_source_authors.create
        author.name = 'Lina Meng'
        author.name_abbr = 'L. Meng'
        author.save

        redirect_to evidence_sources_path
        
    end
    
    def show
        puts "this is show"
        puts params[:id]
    end
    
    def edit
        @evidence_source = EvidenceSource.find(params[:id])
    end
    
    private def evidence_source_params
        params.require(:evidence_source).permit(
            :category, :title, :year, :source_title,
            :publisher, :volume_number, :issue_number, :URL, :DOI)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @the_user = current_user
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evidence_source_authors_helper.rb
module EvidenceSourceAuthorsHelper
end

app/helpers/evidence_sources_helper.rb
module EvidenceSourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/evidence_sources/_bs_form.html.erb
  
<%= bootstrap_form_for :evidence_source, url: evidence_sources_path do |f| %>
  <%= f.text_field :category %>
  <%= f.text_field :title %>
  <%= f.text_field :year %>
  <%= f.text_field :author %>
  <%= f.text_field :source_title %>
  <%= f.text_field :publisher %>
  <%= f.text_field :volume_number %>
  <%= f.text_field :issue_number %>
  <%= f.text_field :page %>
  <%= f.text_field :URL %>
  <%= f.text_field :DOI %>
  <%= f.submit "SUBMIT" %>
<% end %>

app/views/evidence_sources/_index.html.erb
<div>
    <p></P>USER ID: <%= current_user.id %></p>
    <p>EMAIL: <%= current_user.email %></p>
</div>
<div class="list-group">
    <% @evidence_sources.each do |es| %>
        <div class="list-group-item">
            <table class="table table-stripped">
                <tr>
                    <th>title</th>
                    <td><%= es.title %></td>
                </tr>
                <tr>
                    <th>misc</th>
                    <td> ID:<%=es.id%> | <%=es.status%>&nbsp;
                            | category:<%=es.category%>&nbsp;
                            | year:<%=es.year%>&nbsp;
                            | volume:<%=es.volume_number%>&nbsp;
                            | issue:<%=es.issue_number%>&nbsp;
                            | page:<%=es.page_str%>&nbsp;
                    </td>
                </tr>
                <tr>
                    <th>authors</th>
                    <td>
                        <% es.evidence_source_authors.each do |author| %>
                            <%=author.name_abbr%> |
                        <% end %>
                    </td>
                </tr>
                <tr>
                    <th>source</th>
                    <td><%=es.source_title%></td>
                </tr>
                <tr>
                    <th>URL</th>
                    <td><%=es.URL%></td>
                </tr>
                <tr><th>DOI</th><td><%=es.DOI%></td></tr>
                
            </table>
        </div>
    <% end %>
</div>

app/views/evidence_sources/_message_box.html.erb
<div class="modal fade" id="message-box" role="dialog">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Modal Header</h4>
    </div>
    <div class="modal-body">
      <p id="message">Some text in the modal.</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
  
</div>
</div>

app/views/evidence_sources/_new_evidence_item.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header" style="padding:35px 50px;">
      <h4><span class="glyphicon glyphicon-plus"></span> NEW EVIDENCE ITEM</h4>
    </div>
    
    <div class="modal-body" style="padding:40px 50px;">
        <%= bootstrap_form_for :evidence_item, url: welcome_index_path do |f| %>
            <%= f.text_field :benefit %>
            <%= f.text_field :result %>
            <div id="new_evidence_item_context">
                <%= f.text_field :where %>
                <%= f.text_field :when %>
                <%= f.text_field :how %>
                <%= f.text_field :whom %>
                <%= f.text_field :what %>
            </div>
            <%= f.text_field :xxx %>

            <div class="btn-group btn-group-justified">
                <div class="btn-group">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>
                        Create
                    </button>
                </div>
                <div class="btn-group">
                    <button class="btn btn-warning">
                        <span class="glyphicon glyphicon-save"></span>
                        SAVE DRAFT
                    </button>
                </div>
                <div class="btn-group">
                    <button class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                        DISCARD
                    </button>
                </div>
             </div>

        <% end %>
    </div>
    
    <!--
    <div class="modal-footer">
      <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
      <p>Not a member? <a href="#">Sign Up</a></p>
      <p>Forgot <a href="#">Password?</a></p>
    </div>
    -->
  </div>
  
</div>

app/views/evidence_sources/accepted.html.erb
<div class="container">
    <h1>LIST OF ACCEPTED EVIDENCE SOURCES.</h1>
    
    <div class="list-group">
        <% @evidence_sources.each do |es| %>
            <div class="list-group-item">
                <table class="table table-stripped">
                    <tr>
                        <th>title</th>
                        <td>
                            <a href=<%= '/evidence_sources/' + es.id.to_s + '/edit' %> target="_blank">
                                <%= es.title %>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <th>misc</th>
                        <td> ID:<%=es.id%> | <%=es.status%>&nbsp;
                                | category:<%=es.category%>&nbsp;
                                | year:<%=es.year%>&nbsp;
                                | volume:<%=es.volume_number%>&nbsp;
                                | issue:<%=es.issue_number%>&nbsp;
                                | page:<%=es.page_str%>&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <th>authors</th>
                        <td>
                            <% es.evidence_source_authors.each do |author| %>
                                <%=author.name_abbr%> |
                            <% end %>
                        </td>
                    </tr>
                    <tr>
                        <th>source</th>
                        <td><%=es.source_title%></td>
                    </tr>
                    <tr>
                        <th>URL</th>
                        <td>TODO: REMOVE THIS LINE? <%=es.URL%></td>
                    </tr>
                    <tr><th>DOI</th><td><%=es.DOI%></td></tr>
                    
                </table>
            </div>
        <% end %>
    </div>
    
</div>

app/views/evidence_sources/all.html.erb
<div class="container">
<h2>ALL EVIDENCE SOURCES</h2>
<%= render 'index' %>
</div>

app/views/evidence_sources/edit.html.erb
<div class="container">
    <script>
        $().ready(function(){
            console.log("page load down");
            $('#new-evidence-item').click(function(){
                console.log("to create new evience item!");
                $('#new-evidence-item-modal').modal();
            });
        });
    </script>
    <h2>EDIT EVIDENCE SOURCE</h2>
    <div>
        <table class="table table-stripped">
            <tr>
                <th>title</th>
                <td><%= @evidence_source.title %></td>
            </tr>
            <tr>
                <th>misc</th>
                <td> ID:<%=@evidence_source.id%> | <%=@evidence_source.status%>&nbsp;
                        | category:<%=@evidence_source.category%>&nbsp;
                        | year:<%=@evidence_source.year%>&nbsp;
                        | volume:<%=@evidence_source.volume_number%>&nbsp;
                        | issue:<%=@evidence_source.issue_number%>&nbsp;
                        | page:<%=@evidence_source.page_str%>&nbsp;
                </td>
            </tr>
            <tr>
                <th>authors</th>
                <td>
                    <% @evidence_source.evidence_source_authors.each do |author| %>
                        <%=author.name_abbr%> |
                    <% end %>
                </td>
            </tr>
            <tr>
                <th>source</th>
                <td><%=@evidence_source.source_title%></td>
            </tr>
            <tr><th>DOI</th><td><%=@evidence_source.DOI%></td></tr>
            <tr><td></td><td></td></tr>
        </table>
    </div>
    <hr/>
    <div>
        <h2>research design</h2>
        <p>research question or aim</p>
        <p>research method: Case Study, Field Observatin, Experiment, Interview, Survey</p>
        <p>research metrics(measurements)</p>
        <p>research participants: undergraduate students, postgraduate students, practitioners</p>
    </div>
    <hr/>
    <div>
        <div><h2>evidence items</h2><button id="new-evidence-item" class="btn btn-success">Create New</button></div>
        <div class="modal fade" id="new-evidence-item-modal" role="dialog">
            <%= render 'new_evidence_item' %>
        </div>
    </div>
</div>

<hr/>
<%= render 'new_evidence_item' %>

app/views/evidence_sources/index.html.erb
<div class="container">
    <h1>This is the INDEX. <%= link_to 'New Article', new_evidence_source_path %></h1>
    
    <div class="list-group">
        <% @evidence_sources.each do |es| %>
            <div class="list-group-item">
                <table class="table table-stripped">
                    <tr>
                        <th>title</th>
                        <td><%= es.title %></td>
                    </tr>
                    <tr>
                        <th>misc</th>
                        <td> ID:<%=es.id%> | <%=es.state%>&nbsp;
                                | category:<%=es.category%>&nbsp;
                                | year:<%=es.year%>&nbsp;
                                | volume:<%=es.volume_number%>&nbsp;
                                | issue:<%=es.issue_number%>&nbsp;
                                | page:<%=es.page_str%>&nbsp;
                        </td>
                    </tr>
                    <tr>
                        <th>authors</th>
                        <td>
                            <% es.evidence_source_authors.each do |author| %>
                                <%=author.name_abbr%> |
                            <% end %>
                        </td>
                    </tr>
                    <tr>
                        <th>source</th>
                        <td><%=es.source_title%></td>
                    </tr>
                    <tr>
                        <th>URL</th>
                        <td><%=es.URL%></td>
                    </tr>
                    <tr><th>DOI</th><td><%=es.DOI%></td></tr>
                    
                </table>
            </div>
        <% end %>
    </div>
    
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>commiter</th>
                <th>state</th>
                <th>category</th>
                <th>title</th>
                <th>year</th>
                <th>source</th>
                <th>DOI</th>
                <th>volume</th>
                <th>issue</th>
                <th>page</th>
            </tr>
        </thead>
        <tbody>
            <% @evidence_sources.each do |es| %>
            <tr>
                <th><%= es.id %></th>
                <td><%= es.committer %></td>
                <td><%= es.state %></td>
                <td><%= es.category %></td>
                
                <% if es.URL.nil? || es.URL.length == 0 %>
                    <td><%= es.title %></td>
                <% else %>
                    <td><a target="_blank" href="<%= es.URL %>"><%= es.title %></a></td>
                <% end %>
                
                <td><%= es.year %></td>
                <td><%= es.source_title %></td>
                <td><%= es.DOI %></td>
                <td><%= es.volume_number %></td>
                <td><%= es.issue_number %></td>
                <td><%= es.page_str %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    
</div>

app/views/evidence_sources/my_submissions.html.erb
<div class="container">
<h2>LIST OF MY SUBMISSIONS</h2>
<%= render 'index' %>
</div>

app/views/evidence_sources/new.html.erb
<div class="container">

<h2>New Evidence Source</h2>
<%= render 'bs_form' %>

</div>

app/views/evidence_sources/new_submitted.html.erb
<div class="container">
<h2>LIST OF NEW SUBMITTED</h2>
<div>
    <p></P>USER ID: <%= current_user.id %></p>
    <p>EMAIL: <%= current_user.email %></p>
</div>
<div class="list-group">
    <script>
        $().ready(function(){
            console.log('page ready.');

            var on_click = function(event) {
                new_status = $(event.target).data('new-status')
                esid = $(event.target).parents('div[data-esid]').data('esid')
                console.log('evidence source :' + esid);
                console.log('new status ' + new_status);
                
                return;
                
                $.ajax({
                    url: '/evidence_sources/' + esid,
                    type: 'PATCH',
                    data: {status: new_status},
                    success: function() {
                        console.log('patch success');
                        $('#message').text('DONE.');
                        $('#message-box').modal();
                    },
                    error: function() {
                        console.log('ERROR.');
                        $('#message').text('Please refresh the page.');
                        $('#message-box').modal();
                    },
                    complete: function() {
                        console.log('patch complete');
                        $('#message').text('Please refresh the page.');
                        $('#message-box').modal();
                    }
                });
            }
            
            $('.accept-btn').click(on_click);
            $('.reject-btn').click(on_click);
        });
    </script>
    <% @evidence_sources.each do |es| %>
        <div class="list-group-item">
            <table class="table table-stripped">
                <tr>
                    <th>title</th>
                    <td>
                        <div class="row" data-esid="<%= es.id %>">
                            <div class="col-sm-8">
                                <%= es.title %>
                            </div>
                            <div class="col-sm-2">
                                <button type="button" class="accept-btn btn btn-success" data-new-status="ACCEPTED">ACCEPT</button>
                            </div>
                            <div class="col-sm-2">
                                <button type="button" class="reject-btn btn btn-danger" data-new-status="REJECTED">REJECT</button>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>misc</th>
                    <td> ID:<%=es.id%> | <%=es.status%>&nbsp;
                            | category:<%=es.category%>&nbsp;
                            | year:<%=es.year%>&nbsp;
                            | volume:<%=es.volume_number%>&nbsp;
                            | issue:<%=es.issue_number%>&nbsp;
                            | page:<%=es.page_str%>&nbsp;
                    </td>
                </tr>
                <tr>
                    <th>authors</th>
                    <td>
                        <% es.evidence_source_authors.each do |author| %>
                            <%=author.name_abbr%> |
                        <% end %>
                    </td>
                </tr>
                <tr>
                    <th>source</th>
                    <td><%=es.source_title%></td>
                </tr>
                <tr>
                    <th>URL</th>
                    <td><%=es.URL%></td>
                </tr>
                <tr><th>DOI</th><td><%=es.DOI%></td></tr>
                
            </table>
        </div>
    <% end %>
</div>

</div>
<%= render 'message_box' %>

app/views/evidence_sources/published.html.erb
<div class="container">
<h2>LIST OF PUBLISHED</h2>
<%= render 'index' %>
</div>

app/views/evidence_sources/rejected.html.erb
<div class="container">
<h2>LIST OF REJECTED</h2>
<%= render 'index' %>
</div>

app/views/evidence_sources/show.html.erb
<div class="container">
<h2>Show Evidence Source</h2>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
<h1>Welcome</h1>
<hr/>
<p>user-id: <%= @the_user.id %></p>
<p>user-email: <%= @the_user.email %></p>
<hr/>

<h2>links for user</h2>
<%= link_to 'LIST OF MY SUBMISSIONS', evidence_sources_my_submissions_path, target: :_blank %><br/>
<%= link_to 'LIST OF PUBLISHED', evidence_sources_published_path, target: :_blank %><br/>
<%= link_to 'NEW ARTICLE', new_evidence_source_path, target: :_blank %><br/>
<a>SEARCH</a><br/>
<hr/>

<h2>links for moderator</h2>
<%= link_to 'LIST OF NEW SUBMITTED', evidence_sources_new_submitted_path, target: :_blank %><br/>
<hr/>

<h2>links for analyst</h2>
<%= link_to 'LIST OF ACCEPTED', evidence_sources_accepted_path, target: :_blank %><br/>
<hr/>

<h2>links for admistrator</h2>
<%= link_to 'ALL EVIDENC SOURCES', evidence_sources_all_path, target: :_blank %><br/>
<%= link_to 'LIST OF REJECTED', evidence_sources_rejected_path, target: :_blank %><br/>
<hr/>
</div>